spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rdp_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8088
  servlet:
    context-path: /rdp
    multipart:
      max-file-size: 10MB

jwt:
  signer_key: jCBbsOzUT0GjKLK2JiPpsn22tnS/UCGmz6WzqM2OmvYCXT9/PjiyFRVw15ky3rEn
  expiration-time: 86400
